### ISSUE TITLE
Expose address as a label

### ISSUE THREAD

**Issue by PierreZ** [CleverCloud/foundationdb-exporter#3]
While having the processID or the machineID is useful, sometimes it is easier to display the full address `ip:port` as a label.

## Proposal

* add the field `machine_address` for all metrics under `.cluster.machines`, populated with `.cluster.machines[].address`
* add the field `process_address` for all metrics under `.cluster.processes`, populated with `.cluster.processes[].address`

WDYT?

**Comment by AlexandreBrg** [comment]
I believe it makes sense to have better visualisation. In that mindset I'll will add metrics to know the count of process depending on their role (`storage`, `proxy`...)
